"""add lecture transcript summary entity graph tables

Revision ID: 97105d77a496
Revises: 3603ca8bf6f1
Create Date: 2026-03-08 14:51:58.949552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '97105d77a496'
down_revision: Union[str, None] = '3603ca8bf6f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lecture',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('file', 'url', name='lecture_source_type'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('thumbnail_path', sa.Text(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'done', 'error', name='lecture_status'), server_default='pending', nullable=False),
    sa.Column('mode', sa.Enum('instant', 'realtime', name='lecture_mode'), server_default='instant', nullable=False),
    sa.Column('processing_progress', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('processing_progress >= 0 AND processing_progress <= 100', name='ck_lecture_processing_progress_range'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lecture_user_id'), 'lecture', ['user_id'], unique=False)
    op.create_table('entity_graph',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lecture_id', sa.UUID(), nullable=False),
    sa.Column('nodes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('edges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('enriched', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lecture_id'], ['lecture.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_graph_lecture_id'), 'entity_graph', ['lecture_id'], unique=True)
    op.create_table('summary',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lecture_id', sa.UUID(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timecode_start', sa.Float(), nullable=True),
    sa.Column('timecode_end', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lecture_id'], ['lecture.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summary_lecture_id'), 'summary', ['lecture_id'], unique=True)
    op.create_table('transcript',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lecture_id', sa.UUID(), nullable=False),
    sa.Column('segments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lecture_id'], ['lecture.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_lecture_id'), 'transcript', ['lecture_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcript_lecture_id'), table_name='transcript')
    op.drop_table('transcript')
    op.drop_index(op.f('ix_summary_lecture_id'), table_name='summary')
    op.drop_table('summary')
    op.drop_index(op.f('ix_entity_graph_lecture_id'), table_name='entity_graph')
    op.drop_table('entity_graph')
    op.drop_index(op.f('ix_lecture_user_id'), table_name='lecture')
    op.drop_table('lecture')
    # ### end Alembic commands ###